library(ggplot2)
X = read.csv('surface_suction_data.csv')
#ggplot(X, aes(surface, time)) +  geom_point(position = "dodge2")
#ggplot(X, aes(surface, time)) +  geom_point()
ggplot(X, aes(surface, time)) +  geom_jitter(width=0.1, alpha=0.5)
